names = [
    "Abanoub Magdy Munir Shahata",
    "Ibrahim Abdel Basir Gamal Ali Hassan",
    "Ibrahim Mohamed Ibrahim Mohamed",
    "Ahmed Ibrahim Hussein Abdullah Sayed Ahmed",
    "Ahmed Bakri Khalil Mohamed",
    "Ahmed Hatem Mohamed Lotfi Kamel",
    "Ahmed Khaled Hamed Ahmed",
    "Ahmed Sabehy Mohamed Eid",
    "Ahmed Talaat Mohamed Abdel Halim",
    "Ahmed Ali Shaban Ali",
    "Ahmed Awad Omar Awad",
    "Ahmed Mohamed Abdel Latif Hassan",
    "Ahmed Mohamed Abdel Moneim Kassab",
    "Ahmed Mahmoud Hussein Mahmoud",
    "Ahmed Yasser Youssef Ahmed",
    "Osama Gamal Gomaa Ahmed",
    "Osama Mohamed Tawfik Mohamed",
    "Osama Mohamed Mohamed Abdullah",
    "Osama Hisham Adly Ali",
    "Islam Ahmed Kamel Aboud",
    "Islam Mohsen Abdallah Ali",
    "Ismail Magdy Mohamed Hama",
    "Ismahan Salah Ahmed Ali",
    "Alaa Hamdy Shaaban Mahmoud",
    "Alaa Sayed Abdel Karim Abdel Allah",
    "Amneh Ahmed Hussein Mohamed",
    "Amneh Khaled Hassan Abdel Wahab",
    "Amneh Sameer Sadek Ahmed",
    "Amneh Mohamed Sayed Abdel Mageed",
    "Anas Ahmed Ali Amin",
    "Aya Fares Mohamed Mahmoud",
    "George Awad Sayed Awadallah",
    "Habiba Mohamed Rizk Afifi",
    "Khaled Ahmed Mohamed Gouda",
    "Khaled Abdel Aal Saeed Mostafa",
    "Khaled Mohamed Badawi Mohamed",
    "Khedr Mahmoud Mohamed Abdel Aziz",
    "Radhi Hegazi Radhi Shareef",
    "Radwa Mohamed Qaid Mohamed",
    "Rana Ahmed Mohamed Mahmoud",
    "Rawda Ahmed Salah Abdel Salam",
    "Reham Mohamed Ahmed Abdullah",
    "Zohour Diaa El-Din Talaat Waziri",
    "Ziad Ahmed Obeid Badawi",
    "Sama Abdel Azim Adham Mabrouk",
    "Samia Saad Bakr Abdel Tawab",
    "Sandus Omar Ragab Hashem",
    "Sayed Ahmed Zaree Sayed",
    "Sayed Farag Sayed Awad",
    "Shahd Ahmed Bahgat Sadek",
    "Shahd Ahmed Alaa Abdel Alim",
    "Sabry Gamal Mohamed Ibrahim",
    "Abdel Rahman Zakaria Mustafa",
    "Abdel Rahman Abdel Fattah Naji Abdel Fattah",
    "Abdel Rahman Mahmoud Abdel Tawab Hassani",
    "Abdel Aziz Ahmed Abdel Aziz Ibrahim",
    "Abdullah Mohamed Abdel Moneim Mohamed",
    "Abdullah Mahmoud Fouzi Mostafa",
    "Abdullah Abdel Jaleel Lamloom Mahdi",
    "Alaa Ghalib Osman Abu Saif",
    "Alaa Mahmoud Fathi Mahmoud",
    "Ali Ahmed Ali Salem",
    "Ammar Gamal Mohamed Saeed",
    "Omar Mohamed Mohamed El-Desouki",
    "Amr Mohamed Ali Redwan",
    "Qasim Shaban Ali Khalifa",
    "Qasim Obeid Khair Kareem",
    "Marina Safwat Barsem Girgis",
    "Mazen Mohamed Sayed Mohamed Ibrahim",
    "Mohamed Adel Mohamed Taha",
    "Mohamed Ahmed Sayed Abdel Moneim Sayed Ahmed Mubarak",
    "Mohamed Ibrahim Mohamed Ibrahim",
    "Mohamed Ahmed Zaki Atiya",
    "Mohamed Ayman Abdel Zaher Mohamed",
    "Mohamed Tawfik Mostafa Tawfik",
    "Mohamed Khaled Hassan Tawfik",
    "Mohamed Khaled Eissa Ahmed",
    "Mohamed Khamees Sayed Ahmed",
    "Mohamed Sami Hamad Mahmoud",
    "Mohamed Saeed Gaber Mohamed",
    "Mohamed Sharif Fouad Hassan",
    "Mohamed Taha Sayed Qenaawi",
    "Mohamed Atef Ali Hassan",
    "Mohamed Abdel Hakim Mustafa Abdel Aalim",
    "Mohamed Azat Farag Mohamed",
    "Mohamed Omar Ahmed Gomaa",
    "Mohamed Mamdouh Gaber Abdel Aalim",
    "Mohamed Mahdi Nasr Al-Din Abdel Azim",
    "Mahmoud Mohamed Abdel Hamid Abdel Tawab",
    "Mahmoud Ahmed Suleiman Fadel",
    "Mahmoud Ahmed Nasser Mahmoud Moawad",
    "Mahmoud Hassan Mohamed Sayed",
    "Mahmoud Khalef Mahmoud Mostafa",
    "Mahmoud Saeed Sayed Mahmoud Soweilim Al-Najjar",
    "Mahmoud Faisal Mahmoud Hassan",
    "Mahmoud Mohamed Lamloom Mohamed",
    "Mahmoud Mostafa Ahmed Abdel Qawi",
    "Mustafa Osama Mohamed Bakri",
    "Mustafa Mahmoud Amara Abdel Fattah",
    "Muatasim Gamal Mustafa Abdel Azim",
    "Manar Abbas Ahmed Abbas",
    "Menna Mohamed Mohamed Ibrahim",
    "Mahab Ahmed Mohamed Hassan Mahdali",
    "Mai Mohamed Sayed Mahmoud",
    "Nada Yasser Mahmoud Abdel Wahab",
    "Norhan Gamal Mohamed Abdel Wahab",
    "Norhan Hassan Riad Abdel Aal",
    "Norhan Salama Kamel Hassan",
    "Norhan Adel Abdel Hadi Barea",
    "Norhan Abdel Dayem Imam Amin",
    "Hisham Abu Al-Saud Saadik Ahmed",
    "Wessam Khaled Ramadan Hamed",
    "Yemeni Ayman Mohamed Ali",
    "Yemeni Magdy Mohamed Laithi",
    "Yusuf Ahmed Mohamed Ahmed"
]

# Create a DataFrame from the list of names
df = pd.DataFrame(names, columns=["Name"])

# Specify the Excel file name and sheet name
excel_file = "names.xlsx"
sheet_name = "NamesSheet"

# Write the DataFrame to the Excel file
df.to_excel(excel_file, sheet_name=sheet_name, index=False)

print(f"Names have been written to {excel_file}, sheet '{sheet_name}'.")
